# Generated by Django 4.2.4 on 2023-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_area', models.CharField(max_length=150, verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': 'Участки',
                'ordering': ['factory_area'],
            },
        ),
        migrations.CreateModel(
            name='FactoryNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.IntegerField(verbose_name='Заводской номер')),
            ],
            options={
                'verbose_name': 'Заводской номер',
                'verbose_name_plural': 'Заводские номера',
                'ordering': ['factory_number'],
            },
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(verbose_name='Проблема')),
                ('employee_full_name', models.CharField(max_length=150, verbose_name='Ф.И.О. работника')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('factory_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewform.factoryarea', verbose_name='Участок')),
                ('factory_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewform.factorynumber', verbose_name='Заводской номер')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Проблема', to='reviewform.problems', verbose_name='Проблема')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
